# Generated by Django 3.1.2 on 2020-12-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('std_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('roll', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('address', models.TextField(max_length=1200)),
            ],
        ),
    ]
