# Generated by Django 3.1.2 on 2020-12-18 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pannel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Student',
        ),
    ]
